### ISSUE TITLE
OpenCV Installation time

### ISSUE THREAD

**Issue by rishinikhil** [saksham2001/TouchFree-v2#2]
The installation of opencv is taking too much time as per the steps defined on RPi Model 3B+.

tensorflow==2.2.0 is also not getting installed.

Any way around?

**Comment by saksham2001** [comment]
The OpenCV Installation time is not in my hands, it depends upon your internet speed and your devices ram.
For the Installation of Tensorflow please check out the hackster blog [here](https://www.hackster.io/sakshambhutani2001/touchfree-automated-temperature-checkup-and-mask-detection-2cc337)
It is given in detail!
